name: spotify_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0
  flutter_bloc: ^9.0.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.2   # Specify version
  firebase_core: ^3.10.1
  firebase_auth:
  get_it: ^8.0.3
  dartz: ^0.10.1
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  audioplayers: ^6.1.2
  cloud_firestore: ^5.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300
