// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyVxQ2kuLlv7Hn5VuHk5F9S_M3gxoNBY',
    appId: '1:879713373844:web:6c5eaa6af026ec95abae81',
    messagingSenderId: '879713373844',
    projectId: 'spotifyclone-7fec9',
    authDomain: 'spotifyclone-7fec9.firebaseapp.com',
    storageBucket: 'spotifyclone-7fec9.firebasestorage.app',
    measurementId: 'G-KLCEMECBX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCBXKZZPvCLiEGbtDEwxBsvE8lnh7sWxA',
    appId: '1:879713373844:android:a591175b38b3a357abae81',
    messagingSenderId: '879713373844',
    projectId: 'spotifyclone-7fec9',
    storageBucket: 'spotifyclone-7fec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUXrk6663CasZRKyivCXL22tvhE3Aqiy8',
    appId: '1:879713373844:ios:04751516f8194fa0abae81',
    messagingSenderId: '879713373844',
    projectId: 'spotifyclone-7fec9',
    storageBucket: 'spotifyclone-7fec9.firebasestorage.app',
    iosBundleId: 'com.example.spotify2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUXrk6663CasZRKyivCXL22tvhE3Aqiy8',
    appId: '1:879713373844:ios:04751516f8194fa0abae81',
    messagingSenderId: '879713373844',
    projectId: 'spotifyclone-7fec9',
    storageBucket: 'spotifyclone-7fec9.firebasestorage.app',
    iosBundleId: 'com.example.spotify2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFyVxQ2kuLlv7Hn5VuHk5F9S_M3gxoNBY',
    appId: '1:879713373844:web:6b364f06ec6199bdabae81',
    messagingSenderId: '879713373844',
    projectId: 'spotifyclone-7fec9',
    authDomain: 'spotifyclone-7fec9.firebaseapp.com',
    storageBucket: 'spotifyclone-7fec9.firebasestorage.app',
    measurementId: 'G-359ED4Q7MG',
  );
}
